### ISSUE TITLE
scrape_publication seems to require full URL

### ISSUE THREAD

**Issue by eagereyes** [otosky/medium_stats#3]
When I'm trying to scrape a publication under a custom URL, that works fine. But a regular publication under medium.com seems to require the full URL (at least including the domain).

So this works:
`scrape_publication -u medium.com/name-of-publication`
while this doesn't:
`scrape_publication -u name-of-publication`

The error is `socket.gaierror: [Errno 8] nodename nor servname provided, or not known`, which to me suggests that the script doesn't prepend the medium.com/ bit.

**Comment by otosky** [comment]
Changes applied in 154d55f73fe139c1e102570fadeb5184a77aea7e
